name: cicd-pipeline
on: [push]
jobs:
  docker-build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        name: docker login
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push image
        run: |
          set -e
          docker buildx build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/homepage:$GITHUB_REF_NAME \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/homepage:$GITHUB_REF_NAME-$GITHUB_RUN_ID \
            --platform linux/amd64,linux/arm/v7,linux/arm64 \
            --push \
            .
  deploy:
    needs: docker-build
    runs-on: ubuntu-22.04
    # if: github.ref == 'refs/heads/master'
    environment: k8s
    steps:
      - uses: actions/checkout@v3

      - uses: azure/setup-kubectl@v3
        name: install kubectl
        with:
          version: v1.26.3

      - name: k8s set cluster
        uses: azure/k8s-set-context@v3
        with:
          method: service-account
          k8s-url: ${{ secrets.K8S_API_URL }}
          k8s-secret: ${{ secrets.K8S_SERVICEACCOUNT_SECRET }}

      - name: set docker image
        env:
          BRANCH_NAME: $GITHUB_REF_NAME
          RUN_ID: $GITHUB_RUN_ID
          DOCKER_REPOSITORY: ${{ secrets.DOCKERHUB_USERNAME }}/homepage
        run: |
          set -e
          yq -i '.spec.template.spec.containers[0].image = $DOCKER_REPOSITORY:$BRANCH_NAME-$RUN_ID' manifests/deployment.yaml

      - uses: Azure/k8s-deploy@v4
        name: deploy homepage
        with:
          namespace: "personal"
          action: deploy
          manifests: |
            manifests
