name: cicd-pipeline
on: [push]

env:
  REGISTRY: docker.io
  REGISTRY_USER: ${{ secrets.DOCKERHUB_USERNAME }}
  REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  docker-build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        name: docker login
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: install podman
        run: |
          echo 'deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/unstable/xUbuntu_22.04/ /' | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:unstable.list
          curl -fsSL https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/xUbuntu_22.04/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/devel_kubic_libcontainers_unstable.gpg > /dev/null
          sudo apt-get update
          sudo apt-get install podman
        shell: bash

      - name: build image
        run: |
          set -e
          export TAG=$(echo $GITHUB_REF_NAME | sed 's|/|-|g')

          /bin/bash ./tools/docker-build.sh "$TAG" "$TAG-$GITHUB_RUN_ID"
        shell: bash
        env:
          CONTAINER_REGISTRY: ${{ env.REGISTRY }}/${{ env.REGISTRY_USER }}
          IMAGE_NAME: homepage

  deploy:
    needs: docker-build
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/master'
    environment: k8s
    steps:
      - uses: actions/checkout@v3

      - uses: azure/setup-kubectl@v3
        name: install kubectl
        with:
          version: v1.26.3

      - name: k8s set cluster
        uses: azure/k8s-set-context@v3
        with:
          method: service-account
          k8s-url: ${{ secrets.K8S_API_URL }}
          k8s-secret: ${{ secrets.K8S_SERVICEACCOUNT_SECRET }}

      - name: set docker image
        env:
          BRANCH_NAME: ${{ github.ref_name }}
          RUN_ID: ${{ github.run_id }}
          DOCKER_REPOSITORY: ${{ secrets.DOCKERHUB_USERNAME }}/homepage
        run: |
          set -e
          yq -i ".spec.template.spec.containers[0].image = \"$DOCKER_REPOSITORY:$BRANCH_NAME-$RUN_ID\"" manifests/deployment.yaml

      - uses: Azure/k8s-deploy@v4
        name: deploy homepage
        with:
          namespace: 'personal'
          action: deploy
          manifests: |
            manifests
