name: cicd-pipeline
on: [push]
jobs:
  docker-build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        name: docker login
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push image
        run: |
          docker buildx build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/homepage:$GITHUB_REF_NAME \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/homepage:$GITHUB_REF_NAME-$GITHUB_RUN_ID \
            --platform linux/amd64,linux/arm/v7,linux/arm64 \
            --push \
            .
